name: food_ordering
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_svg: 2.0.7
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: 4.9.3
  counter_button: 1.0.1
  lottie: 2.6.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/png/
    - assets/json/
  uses-material-design: true

